### PR TITLE
Add option for configuring the maximum line width of PO files

### PR DESCRIPTION
**Pull request by armandciejak**
Issue #28.

### CODE REVIEW

**Comment by armandciejak** [comment]
I don't get why there remains errors in the `sphinx_util.py` file which I didn't modify.

**Comment by tk0miya** [comment]
I fixed the error on #30. Could you rebase this to master branch (or merge master to this)?

**Comment by armandciejak** [comment]
Any chance to get it merged soon? Let me know if I need to improve something.

**Comment by tk0miya** [comment]
ping @shimizukawa again

**Pull request merged**
