### PR TITLE
Provide bilingual versions of documents in Chinese and English

### PR DESCRIPTION
**Pull request by xinetzone**

### CODE REVIEW

**Comment by tk0miya** [comment]
We're using readthedocs.org to publish the document of sphinx-intl. So Chinese document should be also published via readthedocs.org. Please let me know if you have a translated document. I'll connect your project as a Chinese version from official document.

**Comment by xinetzone** [comment]
See&nbsp;daobook/sphinx-intl: Sphinx utility that make it easy to translate and to apply translation. (中文) (github.com)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Takeshi ***@***.***&gt;; 
发送时间: 2021年12月18日(星期六) 中午1:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [sphinx-doc/sphinx-intl] Provide bilingual versions of documents in Chinese and English (PR #59)





 
We're using readthedocs.org to publish the document of sphinx-intl. So Chinese document should be also published via readthedocs.org. Please let me know if you have a translated document. I'll connect your project as a Chinese version from official document.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xinetzone** [comment]
See https://github.com/daobook/sphinx-intl and https://daobook.github.io/sphinx-intl/zh-CN/

**Comment by tk0miya** [comment]
Could you publish it on readthedocs instead of GitHub Pages?

**Comment by xinetzone** [comment]
Read the docs integration has been completed.

**Comment by tk0miya** [comment]
Thanks!
Could you add me and @shimizukawa  as maintainers of the project on the readthedocs?
Usernames are `tk0miya` (https://readthedocs.org/profiles/tk0miya/) and `shimizukawa` (https://readthedocs.org/profiles/shimizukawa/)

**Comment by xinetzone** [comment]
Adding maintainers has been completed.

**Comment by tk0miya** [comment]
Thanks! I conneted your translations from https://sphinx-intl.readthedocs.io/en/master/.
"zh_CN" is added to the language select now!
スクリーンショット 2021-12-19 16 35 53

Thank you for your contribution!

**Pull request closed without merging**
