### PR TITLE
Drop f-string to assure Python 3.5 support

### LINKED ISSUE #67: f-string used in transifex.py, but python 3.5 doesn't support f-string
Checking the [Actions log](https://github.com/sphinx-doc/sphinx-intl/actions/runs/3293946807/jobs/5430963966), I saw the CI failing in Python 3.5 with rasing SyntaxError exception because there of `{TRANSIFEX_CLI_MINIMUM_VERSION}` in the code block in the [line 85 of sphinx_intl/transifex.py](https://github.com/sphinx-doc/sphinx-intl/blob/6b3913fea5a8c9b819818b9b28b6d0d0b6f022b3/sphinx_intl/transifex.py#L85):

```
        msg = textwrap.dedent(f"""\
        An unsupported version of the Transifex CLI was found.
        Version {TRANSIFEX_CLI_MINIMUM_VERSION} or greater is required.
        Please run the below command if you want to use this action:
            $ tx update
        """)
```

f-strings are available since Python 3.6, see [PEP 498](https://peps.python.org/pep-0498/).

 <details>
  <summary>See full error log</summary>
  <pre>
  py35 installdeps: -e.[transifex,test]
  py35 inst: /home/runner/work/sphinx-intl/sphinx-intl/.tox/.tmp/package/1/sphinx-intl-2.1.0.dev20221021.zip
  py35 installed: DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.,alabaster==0.7.12,attrs==22.1.0,Babel==2.9.1,certifi==2021.10.8,chardet==4.0.0,click==7.1.2,docutils==0.16,idna==2.10,imagesize==1.4.1,importlib-metadata==2.1.3,iniconfig==1.1.1,Jinja2==2.11.3,MarkupSafe==1.1.1,mock==3.0.5,packaging==20.9,pathlib2==2.3.7.post1,pluggy==0.13.1,py==1.11.0,Pygments==2.11.2,pyparsing==2.4.7,pytest==6.1.2,pytz==2022.5,requests==2.25.1,six==1.16.0,snowballstemmer==2.2.0,Sphinx==3.5.4,sphinx-intl @ file:///home/runner/work/sphinx-intl/sphinx-intl/.tox/.tmp/package/1/sphinx-intl-2.1.0.dev20221021.zip,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==1.0.3,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,toml==0.10.2,urllib3==1.26.9,zipp==1.2.0
  py35 run-test-pre: PYTHONHASHSEED='1964382961'
  py35 run-test: commands[0] | py.test -v --durations=25
  ============================= test session starts ==============================
  platform linux -- Python 3.5.10, pytest-6.1.2, py-1.11.0, pluggy-0.13.1 -- /home/runner/work/sphinx-intl/sphinx-intl/.tox/py35/bin/python
  cachedir: .tox/py35/.pytest_cache
  rootdir: /home/runner/work/sphinx-intl/sphinx-intl
  collecting ... collected 8 items / 3 errors / 5 selected
  
  ==================================== ERRORS ====================================
  ____________________ ERROR collecting tests/test_cmd_pot.py ____________________
  .tox/py35/lib/python3.5/site-packages/_pytest/python.py:571: in _importtestmodule
      mod = import_path(self.fspath, mode=importmode)
  .tox/py35/lib/python3.5/site-packages/_pytest/pathlib.py:517: in import_path
      importlib.import_module(module_name)
  /opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/importlib/__init__.py:126: in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  <frozen importlib._bootstrap>:985: in _gcd_import
      ???
  <frozen importlib._bootstrap>:968: in _find_and_load
      ???
  <frozen importlib._bootstrap>:957: in _find_and_load_unlocked
      ???
  <frozen importlib._bootstrap>:673: in _load_unlocked
      ???
  .tox/py35/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:171: in exec_module
      exec(co, module.__dict__)
  tests/test_cmd_pot.py:13: in <module>
      from sphinx_intl import commands
  .tox/py35/lib/python3.5/site-packages/sphinx_intl/commands.py:18: in <module>
      from . import transifex
  E     File "/home/runner/work/sphinx-intl/sphinx-intl/.tox/py35/lib/python3.5/site-packages/sphinx_intl/transifex.py", line 93
  E       msg = textwrap.dedent(f"""\
  E           An unsupported version of the Transifex CLI was found.
  E           Version {TRANSIFEX_CLI_MINIMUM_VERSION} or greater is required.
  E           Please run the below command if you want to use this action:
  E             ^
  E   SyntaxError: invalid syntax
  ___________________ ERROR collecting tests/test_transifex.py ___________________
  .tox/py35/lib/python3.5/site-packages/_pytest/python.py:571: in _importtestmodule
      mod = import_path(self.fspath, mode=importmode)
  .tox/py35/lib/python3.5/site-packages/_pytest/pathlib.py:517: in import_path
      importlib.import_module(module_name)
  /opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/importlib/__init__.py:126: in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  <frozen importlib._bootstrap>:985: in _gcd_import
      ???
  <frozen importlib._bootstrap>:968: in _find_and_load
      ???
  <frozen importlib._bootstrap>:957: in _find_and_load_unlocked
      ???
  <frozen importlib._bootstrap>:673: in _load_unlocked
      ???
  .tox/py35/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:171: in exec_module
      exec(co, module.__dict__)
  tests/test_transifex.py:16: in <module>
      from sphinx_intl import transifex
  E     File "/home/runner/work/sphinx-intl/sphinx-intl/.tox/py35/lib/python3.5/site-packages/sphinx_intl/transifex.py", line 93
  E       msg = textwrap.dedent(f"""\
  E           An unsupported version of the Transifex CLI was found.
  E           Version {TRANSIFEX_CLI_MINIMUM_VERSION} or greater is required.
  E           Please run the below command if you want to use this action:
  E   
  E               $ tx update
  E   
  E           """)
  E                                  
  E                                                                 
  E                                                                          
  E                                                                       
  E   
  E                          
  E   
  E             ^
  E   SyntaxError: invalid syntax
  =========================== short test summary info ============================
  ERROR tests/test_cmd_pot.py
  ERROR tests/test_cmd_transifex.py
  ERROR tests/test_transifex.py
  !!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
  ============================== 3 errors in 0.67s ===============================
  </pre>
</details>

### PR DESCRIPTION
**Pull request by rffontenelle**
Fixes #67

### CODE REVIEW

**Comment by rffontenelle** [comment]
@TheTripleV While removing f-string to satisfy Python 3.5, I might have spotted another issue (see [Actions build log](https://github.com/sphinx-doc/sphinx-intl/actions/runs/3298015038/jobs/5439576100)), but I'm not sure: Is the `tx` tool available when running the tests?

**Comment by AA-Turner** [comment]
We should drop 3.5 support instead 

A

**Comment by TheTripleV** [comment]
Whoops, the tx tool isn't available.

Adding a step to the workflow:
```yaml
- name: Install Transifex CLI
  run: |
    curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
    mv tx /usr/local/bin/tx
```
will install the latest version of tx.
Alternatively,
```yaml
- name: Install Transifex CLI
  run: |
    curl -o- https://raw.githubusercontent.com/transifex/cli/v1.4.1/install.sh | bash
    mv tx /usr/local/bin/tx
```
will pin the the version of tx to the most recent version.

**Comment by rffontenelle** [comment]
> We should drop 3.5 support instead

@AA-Turner should there be like a new release warning that Python 3.5 support will be dropped, or we can drop it now?

**Comment by AA-Turner** [comment]
Due to python-requires we can bump as pip will handle the resolution.

A

**Comment by rffontenelle** [comment]
Right. I'll close this PR then, to keep the f-string. Even with my patch the 3.5 version fails with another error... I guess it's probably better to drop support.

**Pull request closed without merging**
